#!/usr/bin/env bash

MEL_EXIT_SUCCESS=0
MEL_EXIT_WARNING=1
MEL_EXIT_ERROR=2

MEL_STATUS_SUCCESS="success"
MEL_STATUS_WARNING="warning"
MEL_STATUS_ERROR="error"

MEL_CODE_OK="MEL_OK"
MEL_CODE_WARNING="MEL_WARNING"
MEL_CODE_ARGUMENT_ERROR="MEL_ARGUMENT_ERROR"
MEL_CODE_MANIFEST_INVALID="MEL_MANIFEST_INVALID"
MEL_CODE_SCHEMA_MALFORMED="MEL_SCHEMA_MALFORMED"
MEL_CODE_PATH_INVALID="MEL_PATH_INVALID"
MEL_CODE_REPOSITORY_INVALID="MEL_REPOSITORY_INVALID"
MEL_CODE_RESOLUTION_INVALID="MEL_RESOLUTION_INVALID"
MEL_CODE_PLAN_INVALID="MEL_PLAN_INVALID"
MEL_CODE_POLICY_INVALID="MEL_POLICY_INVALID"
MEL_CODE_DRY_RUN_INVALID="MEL_DRY_RUN_INVALID"
MEL_CODE_DOCTOR_INVALID="MEL_DOCTOR_INVALID"
MEL_CODE_HEALTH_INVALID="MEL_HEALTH_INVALID"
MEL_CODE_PLUGIN_INVALID="MEL_PLUGIN_INVALID"
MEL_CODE_EXECUTOR_INVALID="MEL_EXECUTOR_INVALID"
MEL_CODE_EXECUTOR_PRODUCTION_FORBIDDEN="MEL_EXECUTOR_PRODUCTION_FORBIDDEN"
