#!/usr/bin/env bash

MEL_EXIT_SUCCESS=0
MEL_EXIT_WARNING=1
MEL_EXIT_ERROR=2

MEL_STATUS_SUCCESS="success"
MEL_STATUS_WARNING="warning"
MEL_STATUS_ERROR="error"

MEL_CODE_OK="MEL_OK"
MEL_CODE_WARNING="MEL_WARNING"
MEL_CODE_ARGUMENT_ERROR="MEL_ARGUMENT_ERROR"
MEL_CODE_MANIFEST_INVALID="MEL_MANIFEST_INVALID"
MEL_CODE_SCHEMA_MALFORMED="MEL_SCHEMA_MALFORMED"
MEL_CODE_PATH_INVALID="MEL_PATH_INVALID"
MEL_CODE_REPOSITORY_INVALID="MEL_REPOSITORY_INVALID"
MEL_CODE_RESOLUTION_INVALID="MEL_RESOLUTION_INVALID"
